Repository pyanderson/roll20_tormenta20_grimoire, pull requests merged in 2025-02, with the labels that each got.

#16 Raças e Magias do Ameaças de Arton
  data/generator/generate_db.py
  data/races/Bugbear.json
  data/races/Centauro.json
  data/races/Ceratops.json
  data/races/Elfo-do-mar.json
  data/races/Finntroll.json
  data/races/Gnoll.json
  data/races/Golem-de-Barro.json
  data/races/Golem-de-Bronze.json
  data/races/Golem-de-Carne.json
  data/races/Golem-de-Espelhos.json
  data/races/Golem-de-Ferro.json
  data/races/Golem-de-Gelo-Eterno.json
  data/races/Golem-de-Pedra.json
  data/races/Golem-de-Sucata.json
  data/races/Golem.json
  data/races/Harpia.json
  data/races/Hobgoblin.json
  data/races/Kaijin.json
  data/races/Kallyanach.json
  data/races/Kappa.json
  data/races/Kobolds.json
  data/races/Mashin.json
  data/races/Meio-orc.json
  data/races/Minauro.json
  data/races/Moreau-Búfalo.json
  data/races/Moreau-Coelho.json
  data/races/Moreau-Coruja.json
  data/races/Moreau-Crocodilo.json
  data/races/Moreau-Gato.json
  data/races/Moreau-Hiena.json
  data/races/Moreau-Leão.json
  data/races/Moreau-Lobo.json
  data/races/Moreau-Morcego.json
  data/races/Moreau-Raposa.json
  data/races/Moreau-Serpente.json
  data/races/Moreau-Urso.json
  data/races/Nagah.json
  data/races/Nezumi.json
  data/races/Ogro.json
  data/races/Orc.json
  data/races/Pteros.json
  data/races/Soterrado.json
  data/races/Tabrachi.json
  data/races/Tengu.json
  data/races/Trog-Anão.json
  data/races/Velocis.json
  data/races/Voracis.json
  data/races/Yidishan.json
  data/spells/1º Círculo.json
  data/spells/2º Círculo.json
  data/spells/4º Círculo.json
  data/spells/5º Círculo.json
  package-lock.json
  package.json
  static/db.json
Labels: enhancement

#17 Corrigir os falsos duplicados
  data/generator/generate_db.py
  data/races/Trog-Anão.json
  data/races/Trog.json
  static/db.json
Labels: fix

#18 Origens Regionais
  data/book/Deuses.json
  data/book/Equipamento.json
  data/book/Habilidades.json
  data/book/Origens.json
  data/book/Tabelas.json
  data/book/Testes.json
  data/classes/Arcanista.json
  data/classes/Bardo.json
  data/classes/Bucaneiro.json
  data/classes/Bárbaro.json
  data/classes/Cavaleiro.json
  data/classes/Clérigo.json
  data/classes/Druida.json
  data/classes/Guerreiro.json
  data/classes/Inventor.json
  data/classes/Ladino.json
  data/classes/Lutador.json
  data/classes/Nobre.json
  data/classes/Paladino.json
  data/equipments/Armaduras & Escudos.json
  data/equipments/Armas.json
  data/equipments/Itens Gerais.json
  data/generator/generate_db.py
  data/powers/Origens.json
  data/powers/Poderes Concedidos.json
  data/powers/Poderes da Tormenta.json
  data/powers/Poderes de Combate.json
  data/powers/Poderes de Destino.json
  data/races/Dahllan.json
  data/races/Goblin.json
  data/races/Hynne.json
  data/races/Kliren.json
  data/races/Lefou.json
  data/races/Medusa.json
  data/races/Minotauro.json
  data/races/Qareen.json
  data/races/Suraggel-Aggelus.json
  data/races/Suraggel-Sulfure.json
  data/races/Sílfide.json
  data/races/Trog-Anão.json
  data/races/Trog.json
  data/spells/1º Círculo.json
  data/spells/2º Círculo.json
  data/spells/3º Círculo.json
  data/spells/4º Círculo.json
  data/spells/5º Círculo.json
  static/db.json
Labels: enhancement, fix
